# Generated by Django 2.0 on 2018-09-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0002_remove_preinterviewmodel_weekday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekday',
            old_name='name',
            new_name='weekdeays',
        ),
    ]
