# Generated by Django 2.0 on 2018-09-13 15:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0003_auto_20180913_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='preinterviewmodel',
            name='my_field',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default=0, max_length=49),
        ),
        migrations.AddField(
            model_name='preinterviewmodel',
            name='my_field2',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Item title 2.1'), (2, 'Item title 2.2'), (3, 'Item title 2.3'), (4, 'Item title 2.4'), (5, 'Item title 2.5')], default=0, max_length=3),
        ),
    ]
