# Generated by Django 2.0 on 2018-09-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0004_auto_20180913_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preinterviewmodel',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='preinterviewmodel',
            name='my_field2',
        ),
    ]
