# Generated by Django 2.0 on 2018-09-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0005_auto_20180914_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeekDay',
        ),
        migrations.AddField(
            model_name='preinterviewmodel',
            name='week_day',
            field=models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tus', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default=('sun', 'Sunday'), max_length=100),
        ),
    ]
