# Generated by Django 2.0 on 2018-09-14 05:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0006_auto_20180914_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinterviewmodel',
            name='week_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tus', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default=('sun', 'Sunday'), max_length=27),
        ),
    ]
