# Generated by Django 2.0 on 2018-09-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0007_auto_20180914_0549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preinterviewmodel',
            old_name='currentsalary',
            new_name='current_salary',
        ),
        migrations.RenameField(
            model_name='preinterviewmodel',
            old_name='jointime',
            new_name='join_time',
        ),
        migrations.RenameField(
            model_name='preinterviewmodel',
            old_name='salaryexpection',
            new_name='salary_expection',
        ),
        migrations.RenameField(
            model_name='preinterviewmodel',
            old_name='whyjoin',
            new_name='why_join',
        ),
    ]
