# Generated by Django 2.0 on 2018-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preinterviewqaapp', '0011_auto_20180914_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preinterviewmodel',
            name='interested_job',
            field=models.CharField(choices=[('android', 'Android app developer'), ('php', 'PHP Expert (CakePHP/CodeIgniter)'), ('python', 'Python Expert'), ('react', 'React Native Expert'), ('web', 'Web Designer (Photoshop/HTML/CSS/Flash)'), ('iphone', 'iPhone app developer')], max_length=128),
        ),
    ]
